import { useLocation } from "react-router-dom";

// Both locales render the same React pages; only text is translated.
export function useSiteLanguage(): "fr" | "en" {
  const { pathname } = useLocation();
  return pathname === "/en" || pathname.startsWith("/en/") ? "en" : "fr";
}

const EN: Record<string, string> = {
  "Accueil": "Home", "Tournois": "Tournaments", "Classement": "Rankings", "Actualités": "News",
  "Connexion": "Sign in", "Créer un compte": "Create account", "Mon compte": "My account",
  "Mon profil": "My profile", "Mes inscriptions": "My registrations", "Mes points": "My points",
  "Paramètres": "Settings", "Déconnexion": "Sign out", "Compte": "Account",
  "Joue. Affronte. Gagne.": "Play. Compete. Win.",
  "Compétition": "Competition", "Voir les tournois": "Browse tournaments",
  "Rejoindre Discord": "Join Discord", "Créer un compte eGame": "Create an eGame account",
  "Tous les tournois →": "All tournaments →", "Aucun tournoi annoncé pour le moment.": "No tournaments announced at the moment.",
  "Les résultats des événements passés restent consultables dans l’historique.": "Past event results remain available in the history.",
  "Simple et accessible": "Simple and accessible", "Comment ça marche": "How it works",
  "En savoir plus →": "Learn more →", "Crée ton compte": "Create your account",
  "Inscris-toi et complète ton profil joueur.": "Sign up and complete your player profile.",
  "Choisis un tournoi": "Choose a tournament", "Consulte les tournois ouverts et leurs conditions.": "Browse open tournaments and their conditions.",
  "Confirme ton inscription": "Confirm your registration", "Choisis un moyen de paiement disponible pour le tournoi.": "Choose an available payment method.",
  "Rejoins la compétition": "Join the competition", "Suis les informations du tournoi et joue à l’heure prévue.": "Follow tournament updates and play at the scheduled time.",
  "Jeux pris en charge": "Supported games", "Jeux de la communauté": "Community games",
  "Les tournois disponibles sont annoncés séparément selon leur calendrier.": "Tournament availability is announced separately.",
  "Tournoi actif": "Active tournament", "Communauté officielle": "Official community",
  "Suivre sur TikTok": "Follow on TikTok", "Devenir partenaire": "Become a partner",
  "À propos": "About", "Contact": "Contact", "Mentions légales": "Legal notice",
  "Confidentialité & conditions": "Privacy & terms", "Informations légales et conditions": "Legal information and terms",
  "Jeu de la communauté": "Community game",
  "Historique / Résultats": "History / Results",
  "Tournois en cours": "Ongoing tournaments",
  "Tournois ouverts": "Open tournaments",
  "Historique": "History",
  "Aucun tournoi annoncé pour ce jeu pour le moment.": "No tournament has been announced for this game yet.",
  "Serveur Discord": "Discord server",
  "Le Mag eSport": "eSports Magazine",
  "Actualités, tournois et conseils eGame Bénin": "eGame Bénin news, tournaments and tips",
  "Aucun article pour le moment.": "No articles yet.",
  "L'équipe eGame Bénin répond à toutes tes questions 7j/7": "The eGame Bénin team is here to help every day",
  "Serveur Discord": "Discord server",
  "Rejoindre maintenant": "Join now",
  "Support E-mail": "Email support",
  "Officiel": "Official",
  "Page Facebook": "Facebook page",
  "Actualités": "News",
  "Suivez eGame Bénin": "Follow eGame Bénin",
  "TikTok officiel": "Official TikTok",
  "Serveur principal eGame Bénin": "Main eGame Bénin server",
  "Support, annonces et communauté": "Support, announcements and community",
  "Mes Inscriptions": "My registrations",
  "Aucune inscription enregistrée.": "No registrations yet.",
  "Ticket eGame Bénin": "eGame Bénin ticket",
  "Fondateur de eGame Bénin": "Founder of eGame Bénin",
  "Plateforme de compétition": "Competition platform",
  "Des outils numériques pour participer aux tournois et suivre sa progression.": "Digital tools to join tournaments and track your progress.",
  "Communauté gaming": "Gaming community",
  "Des joueurs et communautés réunis autour du fair-play et de compétitions organisées.": "Players and communities brought together through fair play and organized competitions.",
  "Événements physiques": "In-person events",
  "Nous ambitionnons d’organiser progressivement des événements gaming et e-sport au Bénin.": "We aim to gradually organize gaming and esports events in Benin.",
  "Une compétition organisée": "Organized competitions",
  "Règles publiées": "Published rules",
  "Chaque tournoi présente ses règles et conditions.": "Each tournament has its own published rules and conditions.",
  "Résultats validés": "Verified results",
  "Communauté eGame": "eGame community",
  "Retrouve les joueurs et l'équipe sur Discord.": "Meet players and our team on Discord.",
  "Vérifiez vos mails": "Check your email",
  "Ou par e-mail": "Or continue with email",
  "Pseudo de Joueur": "Player username",
  "Pays": "Country",
  "Numéro Mobile Money": "Mobile Money number",
  "Adresse E-mail": "Email address",
  "Mot de passe": "Password",
  "Oublié ?": "Forgot?",
  "Nouveau lien de confirmation envoyé !": "New confirmation link sent!",
  "Connexion réussie !": "Signed in successfully!",
  "Le pseudo doit faire au moins 3 caractères.": "Username must contain at least 3 characters.",
  "Sélectionne ton pays pour créer ton compte.": "Select your country to create an account.",
  "Un compte existe déjà avec cet e-mail. Connecte-toi directement.": "An account already exists with this email. Please sign in.",
  "Compte créé !": "Account created!",
  "Tournois": "Tournaments",
  "Points": "Points",
  "Victoires": "Wins",
  "Numéro Mobile Money": "Mobile Money number",
  "Dashboard Administration": "Administration dashboard",
  "Historique des Inscriptions": "Registration history",
  "Modifier mon profil": "Edit my profile",
  "Déconnexion": "Sign out",
  "Déconnexion réussie !": "Signed out successfully!",
  "Notifications désactivées.": "Notifications disabled.",
  "Notifications activées !": "Notifications enabled!",
  "Inscription collective": "Team registration",
  "Gérer mon équipe et demander l'inscription": "Manage my team and request registration",
  "Champion Officiel — 1ère place": "Official champion — 1st place",
  "2ème place": "2nd place",
  "3ème place": "3rd place",
  "MVP du tournoi": "Tournament MVP",
  "Remplissage du tournoi": "Tournament capacity",
  "Inscription Validée !": "Registration confirmed!",
  "Tournoi complet": "Tournament full",
  "Inscriptions bientôt ouvertes": "Registration opens soon",
  "Inscriptions Closes": "Registration closed",
  "Un paiement est déjà en cours": "A payment is already in progress",
  "As-tu été débité pour cette tentative ?": "Were you charged for this attempt?",
  "Avant de continuer": "Before continuing",
  "Choix du Paiement": "Choose a payment method",
  "Sélectionne ton moyen de paiement préféré": "Select your preferred payment method",
  "Mobile Money et carte bancaire selon les moyens disponibles": "Mobile Money and bank cards, depending on availability",
  "Paiement sécurisé via Moneroo": "Secure payment via Moneroo",
  "Ton ticket est prêt !": "Your ticket is ready!",
  "Préparation...": "Preparing...",
  "100% gratuit": "100% free",
  "ticket personnel": "personal ticket",
  "Mentions légales": "Legal notice",
  "Informations légales • eGame Bénin": "Legal information • eGame Bénin",
  "Éditeur de la plateforme": "Platform publisher",
  "Hébergement": "Hosting",
  "Toute réclamation ou demande d'information :": "For any complaint or information request:",
  "Politique de confidentialité": "Privacy policy",
  "Conditions, confidentialité & remboursements": "Terms, privacy & refunds",
  "Conditions Générales & Protection des Données • v1.1": "Terms and data protection • v1.1",
  "1. Conditions d'Utilisation": "1. Terms of use",
  "Acceptation des conditions": "Acceptance of terms",
  "Description du service": "Service description",
  "Responsabilité de l'utilisateur": "User responsibility",
  "Propriété intellectuelle": "Intellectual property",
  "2. Règles de l'Arène": "2. Arena rules",
  "3. Politique de Confidentialité": "3. Privacy policy",
  "Données collectées": "Data collected",
  "Sécurité des paiements": "Payment security",
  "Vos droits": "Your rights",
  "4. Inscriptions & Remboursements": "4. Registration & refunds",
  "Nous accordons une importance capitale à la protection de vos données personnelles.": "Protecting your personal data is a top priority.",
  "Proposition bien envoyée !": "Proposal sent successfully!",
  "Nom / prénom *": "Full name *",
  "Entreprise, organisation, clan ou communauté *": "Company, organization, clan or community *",
  "E-mail *": "Email *",
  "Numéro de téléphone *": "Phone number *",
  "Type de partenariat *": "Partnership type *",
  "Jeu concerné": "Related game",
  "Lien site / réseau / groupe": "Website / social / group link",
  "Taille de la communauté": "Community size",
  "Ce que tu souhaites apporter *": "What you can contribute *",
  "Ce que tu recherches dans la collaboration *": "What you expect from the partnership *",
  "Budget envisagé": "Expected budget",
  "Message / proposition détaillée *": "Detailed proposal *",
  "Nous étudions également les collaborations sur mesure.": "We also consider customized partnerships.",
  "Choisis un type": "Choose a type",
  "Non applicable": "Not applicable",
  "Ton nom complet": "Your full name",
  "Ex: 350 membres": "E.g. 350 members",
  "Financement, matériel, connexion, couverture média, mobilisation de joueurs, expertise…": "Funding, equipment, connectivity, media coverage, player mobilization, expertise…",
  "Visibilité, statut officiel, contenus, présence événementielle…": "Visibility, official status, content, event participation…",
  "Présente ton idée de collaboration : format, objectifs, calendrier…": "Describe your partnership idea: format, goals, timeline…",
  "(si applicable)": "(if applicable)",
  "(si sponsor financier, facultatif)": "(if financial sponsor, optional)",
  "Partenaires": "Partners", "Étape": "Step",
  "Les tournois sont annoncés séparément selon leur disponibilité.": "Tournaments are announced separately based on availability.",
  "Filtrer par jeu": "Filter by game", "Tous les jeux": "All games",
  "Aucun jeu correspondant.": "No matching games.", "Actif": "Active",
  "Voir les champions": "See champions",
  "Pas encore de classement réel pour ce jeu.": "No confirmed rankings for this game yet.",
  "Le classement apparaîtra dès que des résultats confirmés seront disponibles.": "Rankings will appear as soon as confirmed results are available.",
};
export function translate(text: string, language: "fr" | "en"): string {
  return language === "en" ? EN[text] ?? text : text;
}
