import { useLocation } from "react-router-dom";
import { useCallback } from "react";
import { toEnglishPath } from "@/lib/languageRouting";

// Both locales render the same React pages; only text is translated.
export function useSiteLanguage(): "fr" | "en" {
  const { pathname } = useLocation();
  return pathname === "/en" || pathname.startsWith("/en/") ? "en" : "fr";
}

// Keeps internal links on the same localized route without altering their handlers.
export function useLocalePath(): (destination: string) => string {
  const language = useSiteLanguage();
  return useCallback((destination: string) => {
    if (language !== "en" || !destination.startsWith("/") || destination.startsWith("/en") || destination.startsWith("//")) return destination;
    const match = destination.match(/^([^?#]*)(.*)$/);
    if (!match) return destination;
    return toEnglishPath(match[1]) + match[2];
  }, [language]);
}

const EN: Record<string, string> = {
  "Accueil": "Home", "Tournois": "Tournaments", "Classement": "Rankings", "Actualités": "News",
  "Connexion": "Sign in", "Créer un compte": "Create account", "Mon compte": "My account",
  "Mon profil": "My profile", "Mes inscriptions": "My registrations", "Mes points": "My points",
  "Paramètres": "Settings", "Déconnexion": "Sign out", "Compte": "Account",
  "Joue. Affronte. Gagne.": "Play. Compete. Win.",
  "Compétition": "Competition", "Voir les tournois": "Browse tournaments",
  "Rejoindre Discord": "Join Discord", "Créer un compte eGame": "Create an eGame account",
  "Tous les tournois →": "All tournaments →", "Aucun tournoi annoncé pour le moment.": "No tournaments announced at the moment.",
  "Les résultats des événements passés restent consultables dans l’historique.": "Past event results remain available in the history.",
  "Simple et accessible": "Simple and accessible", "Comment ça marche": "How it works",
  "En savoir plus →": "Learn more →", "Crée ton compte": "Create your account",
  "Inscris-toi et complète ton profil joueur.": "Sign up and complete your player profile.",
  "Choisis un tournoi": "Choose a tournament", "Consulte les tournois ouverts et leurs conditions.": "Browse open tournaments and their conditions.",
  "Confirme ton inscription": "Confirm your registration", "Choisis un moyen de paiement disponible pour le tournoi.": "Choose an available payment method.",
  "Rejoins la compétition": "Join the competition", "Suis les informations du tournoi et joue à l’heure prévue.": "Follow tournament updates and play at the scheduled time.",
  "Jeux pris en charge": "Supported games", "Jeux de la communauté": "Community games",
  "Les tournois disponibles sont annoncés séparément selon leur calendrier.": "Tournament availability is announced separately.",
  "Tournoi actif": "Active tournament", "Communauté officielle": "Official community",
  "Suivre sur TikTok": "Follow on TikTok", "Devenir partenaire": "Become a partner",
  "À propos": "About", "Contact": "Contact", "Mentions légales": "Legal notice",
  "Confidentialité & conditions": "Privacy & terms", "Informations légales et conditions": "Legal information and terms",
  "Jeu de la communauté": "Community game",
  "Historique / Résultats": "History / Results",
  "Tournois en cours": "Ongoing tournaments",
  "Tournois ouverts": "Open tournaments",
  "Historique": "History",
  "Aucun tournoi annoncé pour ce jeu pour le moment.": "No tournament has been announced for this game yet.",
  "Serveur Discord": "Discord server",
  "Le Mag eSport": "eSports Magazine",
  "Actualités, tournois et conseils eGame Bénin": "eGame Bénin news, tournaments and tips",
  "Aucun article pour le moment.": "No articles yet.",
  "L'équipe eGame Bénin répond à toutes tes questions 7j/7": "The eGame Bénin team is here to help every day",
  "Serveur Discord": "Discord server",
  "Rejoindre maintenant": "Join now",
  "Support E-mail": "Email support",
  "Officiel": "Official",
  "Page Facebook": "Facebook page",
  "Actualités": "News",
  "Suivez eGame Bénin": "Follow eGame Bénin",
  "TikTok officiel": "Official TikTok",
  "Serveur principal eGame Bénin": "Main eGame Bénin server",
  "Support, annonces et communauté": "Support, announcements and community",
  "Mes Inscriptions": "My registrations",
  "Aucune inscription enregistrée.": "No registrations yet.",
  "Ticket eGame Bénin": "eGame Bénin ticket",
  "Fondateur de eGame Bénin": "Founder of eGame Bénin",
  "Plateforme de compétition": "Competition platform",
  "Des outils numériques pour participer aux tournois et suivre sa progression.": "Digital tools to join tournaments and track your progress.",
  "Communauté gaming": "Gaming community",
  "Des joueurs et communautés réunis autour du fair-play et de compétitions organisées.": "Players and communities brought together through fair play and organized competitions.",
  "Événements physiques": "In-person events",
  "Nous ambitionnons d’organiser progressivement des événements gaming et e-sport au Bénin.": "We aim to gradually organize gaming and esports events in Benin.",
  "Une compétition organisée": "Organized competitions",
  "Règles publiées": "Published rules",
  "Chaque tournoi présente ses règles et conditions.": "Each tournament has its own published rules and conditions.",
  "Résultats validés": "Verified results",
  "Communauté eGame": "eGame community",
  "Retrouve les joueurs et l'équipe sur Discord.": "Meet players and our team on Discord.",
  "Vérifiez vos mails": "Check your email",
  "Ou par e-mail": "Or continue with email",
  "Pseudo de Joueur": "Player username",
  "Pays": "Country",
  "Numéro Mobile Money": "Mobile Money number",
  "Adresse E-mail": "Email address",
  "Mot de passe": "Password",
  "Oublié ?": "Forgot?",
  "Nouveau lien de confirmation envoyé !": "New confirmation link sent!",
  "Connexion réussie !": "Signed in successfully!",
  "Le pseudo doit faire au moins 3 caractères.": "Username must contain at least 3 characters.",
  "Sélectionne ton pays pour créer ton compte.": "Select your country to create an account.",
  "Un compte existe déjà avec cet e-mail. Connecte-toi directement.": "An account already exists with this email. Please sign in.",
  "Compte créé !": "Account created!",
  "Tournois": "Tournaments",
  "Points": "Points",
  "Victoires": "Wins",
  "Numéro Mobile Money": "Mobile Money number",
  "Dashboard Administration": "Administration dashboard",
  "Historique des Inscriptions": "Registration history",
  "Modifier mon profil": "Edit my profile",
  "Déconnexion": "Sign out",
  "Déconnexion réussie !": "Signed out successfully!",
  "Notifications désactivées.": "Notifications disabled.",
  "Notifications activées !": "Notifications enabled!",
  "Inscription collective": "Team registration",
  "Gérer mon équipe et demander l'inscription": "Manage my team and request registration",
  "Champion Officiel — 1ère place": "Official champion — 1st place",
  "2ème place": "2nd place",
  "3ème place": "3rd place",
  "MVP du tournoi": "Tournament MVP",
  "Remplissage du tournoi": "Tournament capacity",
  "Inscription Validée !": "Registration confirmed!",
  "Tournoi complet": "Tournament full",
  "Inscriptions bientôt ouvertes": "Registration opens soon",
  "Inscriptions Closes": "Registration closed",
  "Un paiement est déjà en cours": "A payment is already in progress",
  "As-tu été débité pour cette tentative ?": "Were you charged for this attempt?",
  "Avant de continuer": "Before continuing",
  "Choix du Paiement": "Choose a payment method",
  "Sélectionne ton moyen de paiement préféré": "Select your preferred payment method",
  "Mobile Money et carte bancaire selon les moyens disponibles": "Mobile Money and bank cards, depending on availability",
  "Paiement sécurisé via Moneroo": "Secure payment via Moneroo",
  "Ton ticket est prêt !": "Your ticket is ready!",
  "Préparation...": "Preparing...",
  "100% gratuit": "100% free",
  "ticket personnel": "personal ticket",
  "Mentions légales": "Legal notice",
  "Informations légales • eGame Bénin": "Legal information • eGame Bénin",
  "Éditeur de la plateforme": "Platform publisher",
  "Hébergement": "Hosting",
  "Toute réclamation ou demande d'information :": "For any complaint or information request:",
  "Politique de confidentialité": "Privacy policy",
  "Conditions, confidentialité & remboursements": "Terms, privacy & refunds",
  "Conditions Générales & Protection des Données • v1.1": "Terms and data protection • v1.1",
  "1. Conditions d'Utilisation": "1. Terms of use",
  "Acceptation des conditions": "Acceptance of terms",
  "Description du service": "Service description",
  "Responsabilité de l'utilisateur": "User responsibility",
  "Propriété intellectuelle": "Intellectual property",
  "2. Règles de l'Arène": "2. Arena rules",
  "3. Politique de Confidentialité": "3. Privacy policy",
  "Données collectées": "Data collected",
  "Sécurité des paiements": "Payment security",
  "Vos droits": "Your rights",
  "4. Inscriptions & Remboursements": "4. Registration & refunds",
  "Nous accordons une importance capitale à la protection de vos données personnelles.": "Protecting your personal data is a top priority.",
  "Proposition bien envoyée !": "Proposal sent successfully!",
  "Nom / prénom *": "Full name *",
  "Entreprise, organisation, clan ou communauté *": "Company, organization, clan or community *",
  "E-mail *": "Email *",
  "Numéro de téléphone *": "Phone number *",
  "Type de partenariat *": "Partnership type *",
  "Jeu concerné": "Related game",
  "Lien site / réseau / groupe": "Website / social / group link",
  "Taille de la communauté": "Community size",
  "Ce que tu souhaites apporter *": "What you can contribute *",
  "Ce que tu recherches dans la collaboration *": "What you expect from the partnership *",
  "Budget envisagé": "Expected budget",
  "Message / proposition détaillée *": "Detailed proposal *",
  "Nous étudions également les collaborations sur mesure.": "We also consider customized partnerships.",
  "Choisis un type": "Choose a type",
  "Non applicable": "Not applicable",
  "Ton nom complet": "Your full name",
  "Ex: 350 membres": "E.g. 350 members",
  "Financement, matériel, connexion, couverture média, mobilisation de joueurs, expertise…": "Funding, equipment, connectivity, media coverage, player mobilization, expertise…",
  "Visibilité, statut officiel, contenus, présence événementielle…": "Visibility, official status, content, event participation…",
  "Présente ton idée de collaboration : format, objectifs, calendrier…": "Describe your partnership idea: format, goals, timeline…",
  "(si applicable)": "(if applicable)",
  "(si sponsor financier, facultatif)": "(if financial sponsor, optional)",
  "Retour": "Back",
  "Dernière mise à jour : 4 Mars 2026": "Last updated: March 4, 2026",
  "En accédant à l'application eGame Bénin, vous acceptez d'être lié par les présentes conditions, toutes les lois et réglementations applicables au Bénin, et acceptez que vous êtes responsable du respect des lois locales applicables.": "By accessing eGame Bénin, you agree to these terms and all applicable laws and regulations in Benin. You are responsible for complying with applicable local laws.",
  "eGame Bénin est une plateforme d'organisation de tournois de jeux vidéo. Nous fournissons l'infrastructure pour l'inscription, le paiement des frais de participation et la gestion des classements.": "eGame Bénin is a video game tournament platform. We provide infrastructure for registration, entry fee payments, and leaderboard management.",
  "Vous êtes responsable du maintien de la confidentialité de votre compte et de votre mot de passe. Vous acceptez de ne pas utiliser la plateforme pour des activités illégales ou frauduleuses.": "You are responsible for keeping your account and password secure. You agree not to use the platform for illegal or fraudulent activities.",
  "Le contenu, le logo, les graphismes et le code de l'application sont la propriété exclusive de eGame Bénin. Toute reproduction sans autorisation est interdite.": "The content, logo, graphics, and application code are the exclusive property of eGame Bénin. Unauthorized reproduction is prohibited.",
  "Respect absolu envers les adversaires et les administrateurs. Les insultes mènent au bannissement.": "Respect other players and administrators. Abusive language may lead to a ban.",
  "L'usage de hacks, scripts ou exploitation de bugs entraîne une disqualification immédiate et définitive.": "Using hacks, scripts, or exploiting bugs leads to immediate and permanent disqualification.",
  "Un retard de plus de 10 minutes lors d'un match programmé entraîne un forfait automatique.": "Being more than 10 minutes late for a scheduled match results in an automatic forfeit.",
  "Nous collectons uniquement les informations nécessaires au fonctionnement du service : Email (authentification), Pseudo (affichage), et Numéro de téléphone (contact pour les prix et support).": "We only collect information needed to operate the service: email (authentication), username (display), and phone number (prizes and support contact).",
  "Les paiements sont traités par des prestataires de paiement sécurisés. Les moyens disponibles peuvent varier selon le tournoi. eGame Bénin n'a jamais accès à vos codes PIN ou informations de carte bancaire.": "Payments are processed by secure payment providers. Available methods vary by tournament. eGame Bénin never accesses your PIN or bank card details.",
  "Conformément à la législation sur la protection des données, vous disposez d'un droit d'accès, de rectification et de suppression de vos données personnelles via les paramètres de votre profil.": "Subject to applicable data protection law, you can access, correct, or delete your personal information through your profile settings.",
  "• Les frais d'inscription sont définitifs et non remboursables une fois le tournoi commencé.": "• Entry fees are final and non-refundable once a tournament has started.",
  "• En cas d'annulation d'un tournoi par l'administration, les participants seront intégralement remboursés ou crédités pour un futur événement.": "• If administrators cancel a tournament, participants receive a full refund or credit for a future event.",
  "• Les récompenses sont versées après validation définitive des résultats, selon les conditions du tournoi.": "• Prizes are awarded after final results are verified, subject to tournament rules.",
  "Pour toute question concernant ces conditions, contactez-nous à :": "For questions about these terms, contact us at:",
  "Fair-Play :": "Fair play:",
  "Anti-Triche :": "Anti-cheating:",
  "Ponctualité :": "Punctuality:",
  "Dernière mise à jour : 15 Septembre 2026": "Last updated: September 15, 2026",
  "Retour": "Back",
  "Plateforme": "Platform",
  "Responsable": "Person in charge",
  "Pays": "Country",
  "Site web": "Website",
  "Les références d'immatriculation ci-dessus peuvent être vérifiées auprès du Guichet Unique de formalités des entreprises du Bénin (APIEx).": "The registration details above can be verified with Benin's one-stop business formalities service (APIEx).",
  "Les paiements sont traités par des prestataires de paiement sécurisés.": "Payments are processed by secure payment providers.",
  "Le site egamebenin.com est hébergé par": "The egamebenin.com website is hosted by",
  "Les services backend (authentification, base de données et fonctions serveur) sont fournis par": "Backend services (authentication, database, and server functions) are provided by",
  "Tournoi par équipes de": "Team tournament for",
  "joueurs": "players",
  "Crée ton équipe ou rejoins celle de ton capitaine. L'inscription collective reste soumise à validation administrative, sans ticket automatique.": "Create a team or join your captain's team. Team registration requires administrator approval and does not issue tickets automatically.",
  "Tournoi d'essai — visible uniquement par l'administration. Il n'est pas comptabilisé sur le site et sera supprimé définitivement (paiements et tickets inclus) à sa clôture.": "Test tournament — visible only to administrators. It is excluded from site statistics and will be permanently deleted at completion, including payments and tickets.",
  "Voir mon ticket & code sur le profil": "View my ticket and code on my profile",
  "Ton ticket eGame": "Your eGame ticket",
  "Aucune place disponible": "No seats available",
  "Profil à compléter pour s'inscrire": "Complete your profile to register",
  "Ton profil permet les récompenses, le check-in et le versement des gains": "Your profile is needed for rewards, check-ins and prize payments",
  "Compléter mon profil": "Complete my profile",
  "Discord requis pour s'inscrire": "Discord required to register",
  "Annonces, matchs et preuves du tournoi se déroulent sur Discord": "Tournament announcements, matches and proof are handled on Discord",
  "Connecter mon Discord": "Connect my Discord",
  "Déroulement": "Tournament format",
  "Règlement officiel": "Official rules",
  "Vérifie ton solde Mobile Money, tes SMS et ton e-mail avant de répondre. Ne relance pas le paiement si le montant a été débité.": "Check your Mobile Money balance, SMS and email before answering. Do not retry payment if you have already been charged.",
  "Oui, j'ai été débité": "Yes, I was charged",
  "L'ancienne tentative sera annulée, puis le paiement pourra reprendre immédiatement.": "The previous attempt will be canceled, then payment can be restarted immediately.",
  "Fermer sans rien faire": "Close without taking action",
  "Annuler": "Cancel",
  "Copier le code": "Copy code",
  "J'ai compris": "Got it",
  "Ton code est enregistré : les arbitres eGame le vérifient pour réserver ta place.": "Your code has been recorded: eGame referees will verify it to reserve your place.",
  "Toutes les places sont prises": "All places are taken",
  "Les inscriptions sont fermées.": "Registration is closed.",
  "Tu peux consulter les résultats": "You can view the results",
  "Participants Confirmés": "Confirmed participants",
  "Les inscriptions ouvrent le": "Registration opens on",
  "Les inscriptions se sont terminées le": "Registration ended on",
  "Connecte ton compte Discord pour t'inscrire : tu recevras automatiquement": "Connect your Discord account to register: you will automatically receive",
  "l'accès à l'espace privé du tournoi dès ton inscription validée.": "access to the tournament's private space once your registration is approved.",
  "Rejoins le serveur Discord de ton jeu pour suivre la confirmation et rencontrer la communauté.": "Join your game's Discord server to follow confirmation and meet the community.",
  "Mobile Money &amp; Carte": "Mobile Money & Card",
  "Connecte-toi à eGame Bénin": "Sign in to eGame Bénin",
  "Retour au profil": "Back to profile",
  "Programme organisateur": "Organizer program",
  "Devenir organisateur": "Become an organizer",
  "Responsable": "Organizer contact",
  "Nom et prénom légaux *": "Legal first and last name *",
  "Pays de résidence *": "Country of residence *",
  "Contact professionnel *": "Professional contact *",
  "Communauté": "Community",
  "Enregistrer": "Save",
  "Soumettre": "Submit",
  "Connecte-toi à eGame Bénin.": "Sign in to eGame Bénin.",
  "Invitations à traiter": "Invitations requiring action",
  "Accès organisateur suspendu": "Organizer access suspended",
  "Accès réservé aux organisateurs approuvés": "Access restricted to approved organizers",
  "Outils organisateur": "Organizer tools",
  "Mes tournois": "My tournaments",
  "Inviter par pseudo eGame": "Invite by eGame username",
  "Mes communautés": "My communities",
  "Membres acceptés": "Accepted members",
  "Joueurs inscrits": "Registered players",
  "Compétitions organisées": "Tournaments organized",
  "Participants aux compétitions": "Tournament participants",
  "résultats": "results",
  "Des indicateurs issus directement des données réelles de la plateforme.": "Figures based on real platform data.",
  "Nos": "Our",
  "en chiffres": "in numbers",
  "En ligne": "Online",
  "Présentiel": "In person",
  "Gratuit": "Free",
  "Essai": "Test",
  "Ouvert": "Open",
  "À annoncer": "To be announced",
  "S'inscrire • Gratuit": "Register • Free",
  "Lien copié dans le presse-papier !": "Link copied to clipboard!",
  "Besoin d'aide ? Contacte le support eGame Bénin": "Need help? Contact eGame Bénin support",
  "Ma série eGame": "My eGame streak",
  "Configure ton pays pour activer tes récompenses": "Set your country to enable rewards",
  "Présence du jour déjà validée. Reviens demain !": "Today's check-in is already confirmed. Come back tomorrow!",
  "Impossible de valider ta présence pour le moment. Réessaie.": "Your check-in couldn't be confirmed. Please try again.",
  "Erreur inattendue. Réessaie.": "Unexpected error. Try again.",
  "Replier le détail de la série": "Collapse streak details",
  "Déplier le détail de la série": "Expand streak details",
  "Jour validé": "Day completed",
  "Validation...": "Confirming...",
  "🎉 Série terminée !": "🎉 Streak completed!",
  "✅ Présence validée !": "✅ Check-in confirmed!",
  " crédités": " credited",
  " en attente": " pending",
  " • Reviens demain !": " • Come back tomorrow!",
  "Série reprise · Jour 1/7": "New streak · Day 1/7",
  "Réclamer": "Claim",
  "Aucune récompense pour le moment. Termine ton premier tournoi ou complète ta série de 7 jours !": "No rewards yet. Finish your first tournament or complete your 7-day streak!",
  "Liaison facultative pour les espaces privés des tournois": "Optional connection for private tournament spaces",
  "Discord non connecté.": "Discord not connected.",
  "Partenaires": "Partners", "Étape": "Step",
  "Les tournois sont annoncés séparément selon leur disponibilité.": "Tournaments are announced separately based on availability.",
  "Filtrer par jeu": "Filter by game", "Tous les jeux": "All games",
  "Aucun jeu correspondant.": "No matching games.", "Actif": "Active",
  "Voir les champions": "See champions",
  "Pas encore de classement réel pour ce jeu.": "No confirmed rankings for this game yet.",
  "Le classement apparaîtra dès que des résultats confirmés seront disponibles.": "Rankings will appear as soon as confirmed results are available.",
};
export function translate(text: string, language: "fr" | "en"): string {
  return language === "en" ? EN[text] ?? text : text;
}
